<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<!-- Embutir os arquivos .txt dentro do próprio .exe -->
		<EmbeddedResource Include="sozlukler\*.txt" />

		<None Update="sozlukler\*.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Content Include="icon.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="assets\" />
	</ItemGroup>

</Project>